include: 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

julia:1.5:
  extends:
    - .julia:1.5
    - .test
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true
